Name:           ros-indigo-romeo-moveit-actions
Version:        0.0.7
Release:        2%{?dist}
Summary:        ROS romeo_moveit_actions package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-actionlib
Requires:       ros-indigo-geometric-shapes
Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-moveit-core
Requires:       ros-indigo-moveit-planners
Requires:       ros-indigo-moveit-planners-ompl
Requires:       ros-indigo-moveit-plugins
Requires:       ros-indigo-moveit-ros
Requires:       ros-indigo-moveit-ros-planning
Requires:       ros-indigo-moveit-ros-planning-interface
Requires:       ros-indigo-moveit-ros-visualization
Requires:       ros-indigo-moveit-simple-controller-manager
Requires:       ros-indigo-moveit-simple-grasps
Requires:       ros-indigo-object-recognition-msgs
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-std-msgs
BuildRequires:  ros-indigo-actionlib
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cmake-modules
BuildRequires:  ros-indigo-geometric-shapes
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-moveit-core
BuildRequires:  ros-indigo-moveit-ros-planning
BuildRequires:  ros-indigo-moveit-ros-planning-interface
BuildRequires:  ros-indigo-moveit-simple-grasps
BuildRequires:  ros-indigo-moveit-visual-tools
BuildRequires:  ros-indigo-object-recognition-msgs
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-std-msgs

%description
Interaction with objects using MoveIt

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Feb 12 2016 Natalia Lyubova <natalia.lyubova@gmail.com> - 0.0.7-2
- Autogenerated by Bloom

* Fri Feb 12 2016 Natalia Lyubova <natalia.lyubova@gmail.com> - 0.0.7-1
- Autogenerated by Bloom

* Wed Feb 03 2016 Natalia Lyubova <natalia.lyubova@gmail.com> - 0.0.7-0
- Autogenerated by Bloom

* Wed Dec 30 2015 Natalia Lyubova <natalia.lyubova@gmail.com> - 0.0.6-0
- Autogenerated by Bloom

